#
# export MY_OPERATOR_VERSION=${MY_OPERATOR_VERSION:-"1.2.3"}
# echo "MY_OPERATOR_VERSION=${MY_OPERATOR_VERSION}"
#
# export MY_DB_ENGINE_VERSION=${MY_DB_ENGINE_VERSION:-"8.0.0"}
# echo "MY_DB_ENGINE_VERSION=${MY_DB_ENGINE_VERSION}"
