apiVersion: v2
name: provider-percona-postgresql
description: A Helm chart for deploying the OpenEverest provider-percona-postgresql provider
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - openeverest
  - provider
  - database
home: https://github.com/openeverest/provider-percona-postgresql
sources:
  - https://github.com/openeverest/provider-percona-postgresql
maintainers:
  - name: OpenEverest Contributors
dependencies:
  - name: pg-operator
    version: "2.9.0"
    repository: https://percona.github.io/percona-helm-charts/
    condition: pg-operator.enabled
