apiVersion: backup.openeverest.io/v1alpha1
kind: Restore
metadata:
  name: restore-pitr-3-inst-258
spec:
  instanceRef:
    name: inst-258
  dataSource:
    type: Backup
    backup:
      backupRef:
        name: backup-1gw
      pitr:
        type: date
        date: "2026-07-24T10:11:00Z"



